#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "resource_parser82.y".
#

require 'racc/parser'


module Composer

  module Parser

    class ResourceParser < Racc::Parser

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 2, 8, :_reduce_none,
 0, 9, :_reduce_none,
 2, 9, :_reduce_none,
 5, 10, :_reduce_4,
 1, 11, :_reduce_5,
 1, 12, :_reduce_6,
 1, 13, :_reduce_7,
 0, 14, :_reduce_none,
 1, 14, :_reduce_9 ]

racc_reduce_n = 10

racc_shift_n = 16

racc_action_table = [
     1,     4,     6,     8,     9,    11,    13,    15 ]

racc_action_check = [
     0,     2,     3,     4,     5,     9,    10,    12 ]

racc_action_pointer = [
    -2,   nil,     1,    -1,     3,    -2,   nil,   nil,   nil,     2,
     2,   nil,     2,   nil,   nil,   nil ]

racc_action_default = [
   -10,    -2,   -10,    -1,   -10,   -10,    -5,    -3,    16,   -10,
   -10,    -6,    -8,    -7,    -4,    -9 ]

racc_goto_table = [
     2,     3,     7,     5,    10,    12,    14 ]

racc_goto_check = [
     1,     2,     3,     4,     5,     6,     7 ]

racc_goto_pointer = [
   nil,     0,     0,    -1,     0,    -5,    -5,    -6 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :DECLARE => 2,
 :WORD => 3,
 :NUMBER => 4,
 :STRING => 5,
 "#" => 6 }

racc_use_result_var = true

racc_nt_base = 7

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'DECLARE',
'WORD',
'NUMBER',
'STRING',
'"#"',
'$start',
'resources',
'stmts',
'resource',
'wkstation',
'resourcename',
'units',
'description']

Racc_debug_parser = true

##### racc system variables end #####

 # reduce 0 omitted

 # reduce 1 omitted

 # reduce 2 omitted

 # reduce 3 omitted

module_eval <<'.,.,', 'resource_parser82.y', 16
  def _reduce_4( val, _values, result )
										@logger.warn("#{self.class}"){ "RESOURCE is not set enough. [ #{@resource.inspect} ]"} unless @resource.set_enough?
										@logger.info("#{self.class}"){ "RESOURCE [ #{@resource.name} ] was reduced." }
										@resources.push @resource
										@resource=::Composer::TwsObj::Resource.new
   result
  end
.,.,

module_eval <<'.,.,', 'resource_parser82.y', 17
  def _reduce_5( val, _values, result )
 @resource.wkstation=val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'resource_parser82.y', 19
  def _reduce_6( val, _values, result )
 @resource.name=val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'resource_parser82.y', 21
  def _reduce_7( val, _values, result )
 @resource.units=val[0]
   result
  end
.,.,

 # reduce 8 omitted

module_eval <<'.,.,', 'resource_parser82.y', 24
  def _reduce_9( val, _values, result )
 @resource.description=val[0]
   result
  end
.,.,

 def _reduce_none( val, _values, result )
  result
 end

    end   # class ResourceParser

  end   # module Parser

end   # module Composer
