#
# DO NOT MODIFY!!!!
# This file is automatically generated by racc 1.4.5
# from racc grammer file "workstation_parser84.y".
#

require 'racc/parser'


module Composer

  module Parser

    class WorkstationParser < Racc::Parser

##### racc 1.4.5 generates ###

racc_reduce_table = [
 0, 0, :racc_error,
 0, 33, :_reduce_none,
 2, 33, :_reduce_none,
 3, 34, :_reduce_3,
 3, 34, :_reduce_4,
 3, 34, :_reduce_5,
 3, 35, :_reduce_6,
 1, 38, :_reduce_none,
 2, 38, :_reduce_none,
 1, 40, :_reduce_none,
 1, 40, :_reduce_none,
 1, 40, :_reduce_none,
 1, 40, :_reduce_none,
 1, 40, :_reduce_none,
 1, 40, :_reduce_none,
 1, 40, :_reduce_none,
 2, 41, :_reduce_16,
 2, 42, :_reduce_17,
 2, 43, :_reduce_18,
 1, 48, :_reduce_19,
 3, 48, :_reduce_20,
 2, 44, :_reduce_21,
 2, 45, :_reduce_22,
 2, 46, :_reduce_23,
 2, 47, :_reduce_24,
 0, 39, :_reduce_none,
 3, 39, :_reduce_none,
 0, 49, :_reduce_none,
 2, 49, :_reduce_none,
 1, 50, :_reduce_none,
 1, 50, :_reduce_none,
 1, 50, :_reduce_none,
 1, 50, :_reduce_none,
 1, 50, :_reduce_none,
 1, 50, :_reduce_none,
 1, 50, :_reduce_none,
 1, 50, :_reduce_none,
 1, 50, :_reduce_none,
 3, 51, :_reduce_38,
 0, 60, :_reduce_none,
 2, 60, :_reduce_40,
 2, 60, :_reduce_41,
 2, 52, :_reduce_42,
 1, 53, :_reduce_43,
 2, 54, :_reduce_44,
 2, 55, :_reduce_45,
 2, 56, :_reduce_46,
 2, 57, :_reduce_47,
 2, 58, :_reduce_48,
 2, 59, :_reduce_49,
 3, 36, :_reduce_50,
 1, 61, :_reduce_51,
 2, 61, :_reduce_52,
 1, 61, :_reduce_53,
 5, 37, :_reduce_54,
 0, 62, :_reduce_none,
 2, 62, :_reduce_56,
 0, 63, :_reduce_none,
 2, 63, :_reduce_58 ]

racc_reduce_n = 59

racc_shift_n = 92

racc_action_table = [
    88,    68,    70,    91,    53,    27,    29,    14,    33,    60,
    63,    66,    90,    34,    15,    25,    26,    39,    40,    77,
    17,    62,    65,    41,    22,    23,    72,    13,    54,    27,
    29,    37,    44,    38,    46,    47,    48,     2,    49,    25,
    26,    11,     4,     5,    17,     6,    51,    52,    22,    23,
    16,    54,    55,    57,    58,     9,    79,    80,    81,    46,
    83,    84,    85,    86,    87,     7,    50 ]

racc_action_check = [
    82,    56,    56,    88,    44,    11,    11,     8,    12,    56,
    56,    56,    88,    13,     9,    11,    11,    17,    22,    56,
    11,    56,    56,    23,    11,    11,    56,     6,    82,    24,
    24,    15,    24,    15,    25,    26,    27,     1,    29,    24,
    24,     5,     1,     1,    24,     1,    35,    36,    24,    24,
    10,    45,    51,    54,    55,     4,    58,    60,    62,    63,
    65,    68,    70,    72,    77,     2,    34 ]

racc_action_pointer = [
   nil,    37,    65,   nil,    26,    12,    -2,   nil,    -2,    -2,
    41,    -2,    -1,     6,   nil,     2,   nil,   -12,   nil,   nil,
   nil,   nil,   -11,    -6,    22,     5,     6,    11,   nil,     9,
   nil,   nil,   nil,   nil,    41,    31,    18,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   -10,    21,   nil,   nil,   nil,   nil,
   nil,    23,   nil,   nil,    24,    35,    -2,   nil,    27,   nil,
    28,   nil,    29,    30,   nil,    31,   nil,   nil,    32,   nil,
    33,   nil,    34,   nil,   nil,   nil,   nil,    35,   nil,   nil,
   nil,   nil,    -2,   nil,   nil,   nil,   nil,   nil,   -17,   nil,
   nil,   nil ]

racc_action_default = [
    -1,   -59,   -59,    -2,   -59,   -59,   -59,    92,   -59,   -59,
   -59,   -59,   -59,   -55,    -4,   -59,    -3,   -59,   -12,   -13,
   -14,   -15,   -59,   -59,   -25,   -59,   -59,   -59,    -7,   -59,
    -9,   -10,   -11,    -5,   -59,   -59,   -50,   -51,   -53,   -22,
   -21,   -23,    -6,    -8,   -59,   -18,   -19,   -17,   -16,   -24,
   -56,   -59,   -52,   -27,   -59,   -57,   -26,   -20,   -59,   -54,
   -59,   -33,   -59,   -59,   -34,   -59,   -43,   -35,   -59,   -36,
   -59,   -37,   -59,   -28,   -29,   -30,   -31,   -59,   -32,   -58,
   -47,   -46,   -39,   -49,   -44,   -45,   -42,   -48,   -59,   -38,
   -41,   -40 ]

racc_goto_table = [
    45,    28,    75,     8,    12,    24,    42,     1,     3,    56,
    73,    74,    10,    76,    43,    78,    61,    64,    67,    69,
    71,    89,    36,    35,    59,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    82 ]

racc_goto_check = [
    16,     8,    20,     4,     5,     6,     7,     1,     2,    17,
    18,    19,     3,    21,     8,    22,    23,    24,    25,    26,
    27,    28,    29,    30,    31,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    16 ]

racc_goto_pointer = [
   nil,     7,     7,     7,    -1,    -2,    -6,   -18,   -10,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   -25,   -44,   -46,   -45,
   -54,   -43,   -41,   -40,   -39,   -38,   -37,   -36,   -61,     7,
    10,   -31 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    30,
    31,    32,    18,    19,    20,    21,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil ]

racc_token_table = {
 false => 0,
 Object.new => 1,
 :ACCESS => 2,
 :AUTOLINK => 3,
 :BEHINDFIREWALL => 4,
 :CPUCLASS => 5,
 :CPUNAME => 6,
 :DESCRIPTION => 7,
 :DOMAIN => 8,
 :ENDSTMT => 9,
 :FOR => 10,
 :FULLSTATUS => 11,
 :HOST => 12,
 :IGNORE => 13,
 :MAESTRO => 14,
 :MANAGER => 15,
 :MEMBERS => 16,
 :NODE => 17,
 :OS => 18,
 :PARENT => 19,
 :PATH => 20,
 :RESOLVEDEP => 21,
 :SECUREADDR => 22,
 :SECURITYLEVEL => 23,
 :SERVER => 24,
 :STRING => 25,
 :TCPADDR => 26,
 :TIMEZONE => 27,
 :TYPE => 28,
 :WORD => 29,
 "." => 30,
 "@" => 31 }

racc_use_result_var = true

racc_nt_base = 32

Racc_arg = [
 racc_action_table,
 racc_action_check,
 racc_action_default,
 racc_action_pointer,
 racc_goto_table,
 racc_goto_check,
 racc_goto_default,
 racc_goto_pointer,
 racc_nt_base,
 racc_reduce_table,
 racc_token_table,
 racc_shift_n,
 racc_reduce_n,
 racc_use_result_var ]

Racc_token_to_s_table = [
'$end',
'error',
'ACCESS',
'AUTOLINK',
'BEHINDFIREWALL',
'CPUCLASS',
'CPUNAME',
'DESCRIPTION',
'DOMAIN',
'ENDSTMT',
'FOR',
'FULLSTATUS',
'HOST',
'IGNORE',
'MAESTRO',
'MANAGER',
'MEMBERS',
'NODE',
'OS',
'PARENT',
'PATH',
'RESOLVEDEP',
'SECUREADDR',
'SECURITYLEVEL',
'SERVER',
'STRING',
'TCPADDR',
'TIMEZONE',
'TYPE',
'WORD',
'"."',
'"@"',
'$start',
'statements',
'statement',
'cpudef',
'cpuclassstmt',
'domainstmt',
'cpuoptions',
'maestro',
'cpuoption',
'cpudesc',
'os',
'node',
'tcpaddr',
'secureaddr',
'timezone',
'domain',
'hostname',
'maestroopts',
'maestroopt',
'host',
'type',
'ignore',
'autolink',
'behindfirewall',
'securitylevel',
'fullstatus',
'resolvedep',
'server',
'access',
'wkstations',
'domdesc',
'parent']

Racc_debug_parser = true

##### racc system variables end #####

 # reduce 0 omitted

 # reduce 1 omitted

 # reduce 2 omitted

module_eval <<'.,.,', 'workstation_parser84.y', 15
  def _reduce_3( val, _values, result )
									@logger.warn("#{self.class}"){ "CPU is not set enough. [ #{@cpuname.inspect} ]"} unless @cpuname.set_enough?
									@logger.info("#{self.class}"){ "CPU [ #{@cpuname.name} ] was reduced." }
									@cpunames.push @cpuname
									@cpuname=::Composer::TwsObj::CpuName.new
   result
  end
.,.,

module_eval <<'.,.,', 'workstation_parser84.y', 22
  def _reduce_4( val, _values, result )
									@logger.warn("#{self.class}"){ "CPUCLASS is not set enough. [ #{@cpuclass.inspect} ]"} unless @cpuclass.set_enough?
									@logger.info("#{self.class}"){ "CPUCLASS [ #{@cpuclass.cpuclass} ] was reduced." }
									@cpuclasses.push @cpuclass
									@cpuclass=::Composer::TwsObj::CpuClass.new
   result
  end
.,.,

module_eval <<'.,.,', 'workstation_parser84.y', 29
  def _reduce_5( val, _values, result )
									@logger.warn("#{self.class}"){ "DOMAIN is not set enough. [ #{@domain.inspect} ]"} unless @domain.set_enough?
									@logger.info("#{self.class}"){ "DOMAIN [ #{@domain.name} ] was reduced." }
									@domains.push @domain
									@domain=::Composer::TwsObj::Domain.new
   result
  end
.,.,

module_eval <<'.,.,', 'workstation_parser84.y', 31
  def _reduce_6( val, _values, result )
 @cpuname.name=val[0]
   result
  end
.,.,

 # reduce 7 omitted

 # reduce 8 omitted

 # reduce 9 omitted

 # reduce 10 omitted

 # reduce 11 omitted

 # reduce 12 omitted

 # reduce 13 omitted

 # reduce 14 omitted

 # reduce 15 omitted

module_eval <<'.,.,', 'workstation_parser84.y', 45
  def _reduce_16( val, _values, result )
 @cpuname.description=val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'workstation_parser84.y', 48
  def _reduce_17( val, _values, result )
 @cpuname.os=is_valid?(['UNIX','WNT','OTHER'],val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'workstation_parser84.y', 55
  def _reduce_18( val, _values, result )
									@cpuname.node=@hostname_buffer
									@hostname_buffer=""
   result
  end
.,.,

module_eval <<'.,.,', 'workstation_parser84.y', 57
  def _reduce_19( val, _values, result )
 @hostname_buffer+=val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'workstation_parser84.y', 59
  def _reduce_20( val, _values, result )
 @hostname_buffer=@hostname_buffer+val[1]+val[2]
   result
  end
.,.,

module_eval <<'.,.,', 'workstation_parser84.y', 62
  def _reduce_21( val, _values, result )
 @cpuname.tcpaddr=val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'workstation_parser84.y', 65
  def _reduce_22( val, _values, result )
 @cpuname.secureaddr=val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'workstation_parser84.y', 68
  def _reduce_23( val, _values, result )
 @cpuname.timezone=val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'workstation_parser84.y', 71
  def _reduce_24( val, _values, result )
 @cpuname.domain=val[1]
   result
  end
.,.,

 # reduce 25 omitted

 # reduce 26 omitted

 # reduce 27 omitted

 # reduce 28 omitted

 # reduce 29 omitted

 # reduce 30 omitted

 # reduce 31 omitted

 # reduce 32 omitted

 # reduce 33 omitted

 # reduce 34 omitted

 # reduce 35 omitted

 # reduce 36 omitted

 # reduce 37 omitted

module_eval <<'.,.,', 'workstation_parser84.y', 94
  def _reduce_38( val, _values, result )
									@cpuname.host=@hostname_buffer
									@hostname_buffer=""
   result
  end
.,.,

 # reduce 39 omitted

module_eval <<'.,.,', 'workstation_parser84.y', 96
  def _reduce_40( val, _values, result )
 @cpuname.access=val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'workstation_parser84.y', 97
  def _reduce_41( val, _values, result )
 @cpuname.access=val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'workstation_parser84.y', 100
  def _reduce_42( val, _values, result )
 @cpuname.type=is_valid?(['FTA','S-AGENT','X-AGENT'],val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'workstation_parser84.y', 103
  def _reduce_43( val, _values, result )
 @cpuname.ignore=true
   result
  end
.,.,

module_eval <<'.,.,', 'workstation_parser84.y', 106
  def _reduce_44( val, _values, result )
 @cpuname.autolink=is_valid?(['ON','OFF'], val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'workstation_parser84.y', 109
  def _reduce_45( val, _values, result )
 @cpuname.behindfirewall=is_valid?(['ON','OFF'], val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'workstation_parser84.y', 112
  def _reduce_46( val, _values, result )
 @cpuname.securitylevel=is_valid?(['ENABLED','ON','FORCE'],val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'workstation_parser84.y', 115
  def _reduce_47( val, _values, result )
 @cpuname.fullstatus=is_valid?(['ON','OFF'],val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'workstation_parser84.y', 118
  def _reduce_48( val, _values, result )
 @cpuname.resolvedep=is_valid?(['ON','OFF'],val[1])
   result
  end
.,.,

module_eval <<'.,.,', 'workstation_parser84.y', 121
  def _reduce_49( val, _values, result )
 @cpuname.server=val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'workstation_parser84.y', 124
  def _reduce_50( val, _values, result )
 @cpuclass.cpuclass=val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'workstation_parser84.y', 127
  def _reduce_51( val, _values, result )
 @cpuclass.members.push val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'workstation_parser84.y', 129
  def _reduce_52( val, _values, result )
 @cpuclass.members.push val[1]
   result
  end
.,.,

module_eval <<'.,.,', 'workstation_parser84.y', 131
  def _reduce_53( val, _values, result )
 @cpuclass.members.push val[0]
   result
  end
.,.,

module_eval <<'.,.,', 'workstation_parser84.y', 138
  def _reduce_54( val, _values, result )
									@domain.name=val[0]
									@domain.manager=val[3]
   result
  end
.,.,

 # reduce 55 omitted

module_eval <<'.,.,', 'workstation_parser84.y', 141
  def _reduce_56( val, _values, result )
 @domain.description=val[1]
   result
  end
.,.,

 # reduce 57 omitted

module_eval <<'.,.,', 'workstation_parser84.y', 145
  def _reduce_58( val, _values, result )
 @domain.parent=val[1]
   result
  end
.,.,

 def _reduce_none( val, _values, result )
  result
 end

    end   # class WorkstationParser

  end   # module Parser

end   # module Composer
